import AdminFrame from "@/components/AdminFrame";
import { PageHeading, RefreshButton, formatCurrency } from "@/components/AdminUi";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Plus, Save } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

type PlanDraft = { id?: string; name: string; description: string; price: string; duration: string; isLifetime: boolean; isActive: boolean; displayOrder: string };
const emptyDraft: PlanDraft = { name: "", description: "", price: "", duration: "30", isLifetime: false, isActive: true, displayOrder: "50" };

export default function AdminPlans() {
  const utils = trpc.useUtils();
  const query = trpc.admin.plans.useQuery();
  const [draft, setDraft] = useState<PlanDraft | null>(null);
  const save = trpc.admin.savePlan.useMutation({ onSuccess: () => { toast.success("Plano salvo."); setDraft(null); utils.admin.plans.invalidate(); }, onError: error => toast.error(error.message) });
  const toggle = trpc.admin.setPlanActive.useMutation({ onSuccess: () => utils.admin.plans.invalidate(), onError: error => toast.error(error.message) });
  const openEdit = (plan: NonNullable<typeof query.data>[number]) => setDraft({ id: plan.id, name: plan.name, description: plan.description ?? "", price: String((plan.priceCents / 100).toFixed(2)).replace(".", ","), duration: plan.durationDays ? String(plan.durationDays) : "", isLifetime: plan.isLifetime, isActive: plan.isActive, displayOrder: String(plan.displayOrder) });
  const saveDraft = () => { if (!draft) return; const priceCents = Math.round(Number(draft.price.replace(",", ".")) * 100); if (!draft.name.trim() || !Number.isFinite(priceCents) || priceCents < 1) return toast.error("Preencha nome e preço válidos."); save.mutate({ id: draft.id, name: draft.name.trim(), description: draft.description.trim() || null, priceCents, durationDays: draft.isLifetime ? null : Number(draft.duration), isLifetime: draft.isLifetime, isActive: draft.isActive, displayOrder: Number(draft.displayOrder) || 0 }); };
  return <AdminFrame><PageHeading eyebrow="Oferta comercial" title="Planos de assinatura" description="Defina os produtos exibidos no bot e mantenha somente planos que estão disponíveis para compra." action={<div className="flex gap-2"><RefreshButton onClick={() => utils.admin.plans.invalidate()} loading={query.isFetching} /><Button onClick={() => setDraft(emptyDraft)}><Plus className="mr-2 h-4 w-4" />Novo plano</Button></div>} />
    <section className="grid gap-5 lg:grid-cols-2 xl:grid-cols-3">{query.data?.map(plan => <Card key={plan.id} className="border-border/70 bg-card/80"><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-semibold">{plan.name}</p><p className="mt-1 min-h-10 text-sm leading-5 text-muted-foreground">{plan.description || "Sem descrição."}</p></div><Badge variant="outline" className={plan.isActive ? "border-emerald-400/20 bg-emerald-400/10 text-emerald-300" : "border-border text-muted-foreground"}>{plan.isActive ? "Disponível" : "Inativo"}</Badge></div><div className="mt-6 border-y border-border/60 py-4"><p className="text-2xl font-semibold">{formatCurrency(plan.priceCents)}</p><p className="mt-1 text-xs text-muted-foreground">{plan.isLifetime ? "Acesso vitalício" : `${plan.durationDays} dias de acesso`}</p></div><div className="mt-5 flex gap-2"><Button variant="outline" size="sm" className="flex-1 bg-background/35" onClick={() => openEdit(plan)}>Editar</Button><Button variant="outline" size="sm" disabled={toggle.isPending} onClick={() => toggle.mutate({ planId: plan.id, isActive: !plan.isActive })}>{plan.isActive ? "Desativar" : "Ativar"}</Button></div></CardContent></Card>)}{!query.isLoading && query.data?.length === 0 ? <Card className="border-dashed border-border/80"><CardContent className="p-8 text-center text-sm text-muted-foreground">Cadastre o primeiro plano para liberar compras no bot.</CardContent></Card> : null}</section>
    {draft ? <section className="fixed inset-0 z-50 overflow-y-auto bg-background/85 p-4 backdrop-blur-sm"><div className="mx-auto my-8 max-w-xl rounded-3xl border border-border bg-card p-6 shadow-2xl shadow-black/40"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Configuração de oferta</p><h2 className="mt-1 text-xl font-semibold">{draft.id ? "Editar plano" : "Novo plano"}</h2></div><Button variant="ghost" size="sm" onClick={() => setDraft(null)}>Fechar</Button></div><div className="mt-6 grid gap-4"><div><Label htmlFor="plan-name">Nome</Label><Input id="plan-name" className="mt-1.5" value={draft.name} onChange={event => setDraft({ ...draft, name: event.target.value })} /></div><div><Label htmlFor="plan-description">Descrição curta</Label><Textarea id="plan-description" className="mt-1.5" value={draft.description} onChange={event => setDraft({ ...draft, description: event.target.value })} /></div><div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="plan-price">Preço (R$)</Label><Input id="plan-price" className="mt-1.5" inputMode="decimal" value={draft.price} onChange={event => setDraft({ ...draft, price: event.target.value })} /></div><div><Label htmlFor="plan-duration">Duração em dias</Label><Input id="plan-duration" className="mt-1.5" type="number" disabled={draft.isLifetime} value={draft.duration} onChange={event => setDraft({ ...draft, duration: event.target.value })} /></div></div><div><Label htmlFor="plan-order">Ordem de exibição</Label><Input id="plan-order" className="mt-1.5" type="number" value={draft.displayOrder} onChange={event => setDraft({ ...draft, displayOrder: event.target.value })} /></div><div className="flex items-center justify-between rounded-xl border border-border/70 p-4"><div><p className="text-sm font-medium">Acesso vitalício</p><p className="mt-0.5 text-xs text-muted-foreground">Não aplica data de vencimento.</p></div><Switch checked={draft.isLifetime} onCheckedChange={isLifetime => setDraft({ ...draft, isLifetime })} /></div><div className="flex items-center justify-between rounded-xl border border-border/70 p-4"><div><p className="text-sm font-medium">Disponível para compra</p><p className="mt-0.5 text-xs text-muted-foreground">Exibe o plano na lista do bot.</p></div><Switch checked={draft.isActive} onCheckedChange={isActive => setDraft({ ...draft, isActive })} /></div></div><div className="mt-7 flex justify-end gap-2"><Button variant="outline" onClick={() => setDraft(null)}>Cancelar</Button><Button onClick={saveDraft} disabled={save.isPending}><Save className="mr-2 h-4 w-4" />Salvar plano</Button></div></div></section> : null}
  </AdminFrame>;
}
