import AdminFrame from "@/components/AdminFrame";
import { PageHeading, RefreshButton, StatusBadge, formatDate } from "@/components/AdminUi";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Bot, Clock3, Play, Save, ShieldCheck, Webhook } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export default function AdminOperations() {
  const utils = trpc.useUtils();
  const status = trpc.admin.automation.status.useQuery();
  const logs = trpc.admin.auditLogs.useQuery({ limit: 100 });
  const botSettings = trpc.admin.botSettings.useQuery();
  const [presentation, setPresentation] = useState({ startTitle: "", startDescription: "", previewText: "", previewImageUrl: "", ageNotice: "" });
  useEffect(() => {
    if (!botSettings.data) return;
    setPresentation({
      startTitle: botSettings.data.startTitle,
      startDescription: botSettings.data.startDescription,
      previewText: botSettings.data.previewText ?? "",
      previewImageUrl: botSettings.data.previewImageUrl ?? "",
      ageNotice: botSettings.data.ageNotice,
    });
  }, [botSettings.data]);
  const setupWebhook = trpc.admin.automation.configureTelegramWebhook.useMutation({ onSuccess: () => toast.success("Webhook do Telegram configurado."), onError: error => toast.error(error.message) });
  const activate = trpc.admin.automation.activateLifecycle.useMutation({ onSuccess: () => { toast.success("Automação ativada com sucesso."); utils.admin.automation.status.invalidate(); }, onError: error => toast.error(error.message) });
  const runNow = trpc.admin.automation.runNow.useMutation({ onSuccess: result => { toast.success(result.summary); utils.admin.automation.status.invalidate(); utils.admin.auditLogs.invalidate(); }, onError: error => toast.error(error.message) });
  const savePresentation = trpc.admin.saveBotSettings.useMutation({ onSuccess: () => { toast.success("Apresentação do /start atualizada."); utils.admin.botSettings.invalidate(); utils.admin.auditLogs.invalidate(); }, onError: error => toast.error(error.message) });
  const refresh = () => Promise.all([utils.admin.automation.status.invalidate(), utils.admin.auditLogs.invalidate(), utils.admin.botSettings.invalidate()]);
  const canActivate = status.data?.canActivate ?? false;
  return <AdminFrame><PageHeading eyebrow="Confiabilidade" title="Operação e automação" description="Configure o recebimento de eventos e a rotina automática que aplica lembretes, vencimentos e remoções." action={<RefreshButton onClick={refresh} loading={status.isFetching || logs.isFetching} />} />
    <section className="grid gap-5 lg:grid-cols-3"><Card className="border-border/70 bg-card/80"><CardContent className="p-5"><div className="rounded-xl bg-primary/10 p-2.5 text-primary w-fit"><Bot className="h-5 w-5" /></div><h2 className="mt-4 font-semibold">Webhook do Telegram</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Recebe comandos, confirmações de maioridade e interações de compra do bot.</p><Button className="mt-5 w-full" variant="outline" disabled={!canActivate || setupWebhook.isPending} onClick={() => setupWebhook.mutate()}><Webhook className="mr-2 h-4 w-4" />Configurar webhook</Button></CardContent></Card><Card className="border-border/70 bg-card/80"><CardContent className="p-5"><div className="rounded-xl bg-amber-300/10 p-2.5 text-amber-200 w-fit"><Clock3 className="h-5 w-5" /></div><h2 className="mt-4 font-semibold">Ciclo de assinaturas</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Executa a cada hora em UTC para avisar renovações e processar acessos vencidos.</p><Button className="mt-5 w-full" disabled={!canActivate || activate.isPending} onClick={() => activate.mutate()}><ShieldCheck className="mr-2 h-4 w-4" />Ativar automação</Button></CardContent></Card><Card className="border-border/70 bg-card/80"><CardContent className="p-5"><div className="rounded-xl bg-fuchsia-300/10 p-2.5 text-fuchsia-200 w-fit"><Play className="h-5 w-5" /></div><h2 className="mt-4 font-semibold">Executar agora</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Executa manualmente a conferência de lembretes e vencimentos para validação operacional.</p><Button className="mt-5 w-full" variant="outline" disabled={runNow.isPending} onClick={() => runNow.mutate()}><Play className="mr-2 h-4 w-4" />Rodar verificação</Button></CardContent></Card></section>
    {!canActivate ? <div className="mt-5 rounded-2xl border border-amber-400/20 bg-amber-400/10 px-4 py-3 text-sm text-amber-100">Para ativar webhooks e tarefas recorrentes, crie um ponto de controle e publique o projeto. A automação não é configurada no ambiente de desenvolvimento.</div> : null}
    <section className="mt-6"><Card className="border-primary/20 bg-card/80"><CardContent className="p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="rounded-xl bg-primary/10 p-2.5 text-primary w-fit"><Bot className="h-5 w-5" /></div><h2 className="mt-4 font-semibold">Apresentação do /start</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-muted-foreground">Defina a descrição, a prévia textual e uma imagem pública opcional apresentada pelo bot antes da confirmação de maioridade.</p></div><Button onClick={() => savePresentation.mutate({ ...presentation, previewText: presentation.previewText.trim() || null, previewImageUrl: presentation.previewImageUrl.trim() || null })} disabled={savePresentation.isPending || botSettings.isLoading}><Save className="mr-2 h-4 w-4" />Salvar apresentação</Button></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><div><Label htmlFor="start-title">Título</Label><Input id="start-title" className="mt-1.5" value={presentation.startTitle} onChange={event => setPresentation({ ...presentation, startTitle: event.target.value })} /></div><div><Label htmlFor="preview-image">URL pública da imagem de prévia (opcional)</Label><Input id="preview-image" className="mt-1.5" type="url" placeholder="https://..." value={presentation.previewImageUrl} onChange={event => setPresentation({ ...presentation, previewImageUrl: event.target.value })} /></div><div className="lg:col-span-2"><Label htmlFor="start-description">Descrição</Label><Textarea id="start-description" className="mt-1.5 min-h-24" value={presentation.startDescription} onChange={event => setPresentation({ ...presentation, startDescription: event.target.value })} /></div><div className="lg:col-span-2"><Label htmlFor="preview-text">Prévia textual</Label><Textarea id="preview-text" className="mt-1.5 min-h-20" placeholder="Ex.: conteúdos e benefícios que serão mostrados ao usuário." value={presentation.previewText} onChange={event => setPresentation({ ...presentation, previewText: event.target.value })} /></div><div className="lg:col-span-2"><Label htmlFor="age-notice">Aviso de maioridade</Label><Textarea id="age-notice" className="mt-1.5 min-h-20" value={presentation.ageNotice} onChange={event => setPresentation({ ...presentation, ageNotice: event.target.value })} /></div></div></CardContent></Card></section>
    <section className="mt-6 grid gap-6 lg:grid-cols-[.9fr_1.4fr]"><Card className="border-border/70 bg-card/80"><CardContent className="p-5"><h2 className="font-semibold">Estado da rotina</h2><div className="mt-5 space-y-4"><div className="rounded-xl border border-border/70 bg-background/25 p-3.5"><p className="text-xs text-muted-foreground">Situação</p><div className="mt-2"><StatusBadge value={status.data?.job?.isEnabled ? "success" : "warning"} /></div></div><div><p className="text-xs text-muted-foreground">Agendamento</p><p className="mt-1 font-mono text-sm">{status.data?.job?.cronExpression ?? "Não configurado"}</p></div><div><p className="text-xs text-muted-foreground">Última execução</p><p className="mt-1 text-sm">{formatDate(status.data?.job?.lastRunAt, true)}</p></div><div><p className="text-xs text-muted-foreground">Resumo</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{status.data?.job?.lastRunSummary ?? "Sem execução registrada."}</p></div></div></CardContent></Card><Card className="border-border/70 bg-card/80"><CardContent className="p-0"><div className="px-5 py-4"><h2 className="font-semibold">Log operacional</h2><p className="mt-1 text-xs text-muted-foreground">Eventos recentes de pagamentos, acessos e automações.</p></div><div className="max-h-[540px] overflow-auto border-t border-border/70"><table className="w-full min-w-[680px] text-left text-sm"><thead className="sticky top-0 bg-muted/80 text-[11px] uppercase tracking-wider text-muted-foreground"><tr><th className="px-5 py-3 font-medium">Quando</th><th className="px-5 py-3 font-medium">Evento</th><th className="px-5 py-3 font-medium">Status</th><th className="px-5 py-3 font-medium">Detalhe</th></tr></thead><tbody className="divide-y divide-border/60">{logs.data?.map(log => <tr key={log.id}><td className="whitespace-nowrap px-5 py-3.5 text-xs text-muted-foreground">{formatDate(log.createdAt, true)}</td><td className="px-5 py-3.5"><p className="font-medium">{log.action}</p><p className="mt-0.5 text-xs text-muted-foreground">{log.category}</p></td><td className="px-5 py-3.5"><StatusBadge value={log.status} /></td><td className="max-w-[360px] px-5 py-3.5 text-xs leading-5 text-muted-foreground">{log.message ?? "—"}</td></tr>)}{!logs.isLoading && logs.data?.length === 0 ? <tr><td colSpan={4} className="px-5 py-14 text-center text-muted-foreground">Nenhum evento operacional registrado.</td></tr> : null}</tbody></table></div></CardContent></Card></section>
  </AdminFrame>;
}
