export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  appPublicBaseUrl: (process.env.APP_PUBLIC_BASE_URL ?? "").replace(/\/$/, ""),
  evoPayApiKey: process.env.EVOPAY_API_KEY ?? "",
  evoPayApiBaseUrl: "https://pix.evopay.cash",
  telegramBotToken: process.env.TELEGRAM_BOT_TOKEN ?? "",
  telegramGroupChatId: process.env.TELEGRAM_GROUP_CHAT_ID ?? "",
  telegramWebhookSecret: process.env.TELEGRAM_WEBHOOK_SECRET ?? "",
};
